
pdf('uffe sites set up.pdf',width = 5,height=5)
par(mfrow=c(3,3),mar=c(1,1,1,1))
plot(x=0.5,y=0.5,xlim = c(0,1),ylim=c(0,1),pch='C',ylab='',xaxt = 'n',yaxt = 'n')
legend('bottom',legend = '1',bty='n')
plot(x=0.5,y=0.5,xlim = c(0,1),ylim=c(0,1),pch='-',ylab='',xaxt = 'n',yaxt = 'n')
legend('bottom',legend = '2',bty='n')
title('North')
plot(x=0.5,y=0.5,xlim = c(0,1),ylim=c(0,1),pch='C',ylab='',xaxt = 'n',yaxt = 'n')
legend('bottom',legend = '3',bty='n')

plot(x=0.5,y=0.5,xlim = c(0,1),ylim=c(0,1),pch='-',ylab='',xaxt = 'n',yaxt = 'n')
legend('bottom',legend = '4',bty='n')
plot(x=0.5,y=0.5,xlim = c(0,1),ylim=c(0,1),pch='+',ylab='',xaxt = 'n',yaxt = 'n')
legend('bottom',legend = '5',bty='n')
plot(x=0.5,y=0.5,xlim = c(0,1),ylim=c(0,1),pch='-',ylab='',xaxt = 'n',yaxt = 'n')
legend('bottom',legend = '6',bty='n')

plot(x=0.5,y=0.5,xlim = c(0,1),ylim=c(0,1),pch='+',ylab='',xaxt = 'n',yaxt = 'n')
legend('bottom',legend = '7',bty='n')
plot(x=0.5,y=0.5,xlim = c(0,1),ylim=c(0,1),pch='C',ylab='',xaxt = 'n',yaxt = 'n')
legend('bottom',legend = '8',bty='n')
plot(x=0.5,y=0.5,xlim = c(0,1),ylim=c(0,1),pch='+',ylab='',xaxt = 'n',yaxt = 'n')
legend('bottom',legend = '9',bty='n')
dev.off()